wandb_version: 1

alpha:
  desc: null
  value: 0.1
sigma:
  desc: null
  value: 1
K:
  desc: null
  value: 0.88
batch_size:
  desc: null
  value: 1000
architecture:
  desc: null
  value: ASkewSGD
dataset:
  desc: null
  value: LogisticRegression
epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720617636.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.19
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
